esphome:
  name: ble-proxy
  friendly_name: ble-proxy

esp32:
  board: nodemcu-32s # Stick to a Nodemcu-32s (WROOM32) board for compatibility with ESPHome's Bluetooth Proxy feature.
  framework:
    type: esp-idf
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "[YOUR KEY HERE]"

ota:
  - platform: esphome
    password: "[YOUR OTA PASSWORD HERE]"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.0.123 # Change to your desired static IP
    gateway: 192.168.0.1
    subnet: 255.255.255.0

esp32_ble_tracker:
  scan_parameters:
    active: false
    continuous: True

bluetooth_proxy:
  active: true
  connection_slots: 3